apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voiceowl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: voiceowl.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voiceowl-api
                port:
                  number: 80
