variable "region" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "create_node_group" {}
variable "number_of_nodegroups" {}
variable "node_group_name" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "ami_type" {}
variable "capacity_type" {}
variable "instance_types" {}
variable "subnet_ids" {}
variable "role_arn" {} 
variable "node_role_arn" {}
variable "node_group_subnet_id" {}
variable "disk_size" {}